### ISSUE TITLE
Teddy breaks on certain search terms.

### ISSUE THREAD

**Issue by Mehni** [FluffierThanThou/reddit-modlinker#1]
Example here:

https://www.reddit.com/r/RimWorld/comments/71eeym/warcraft_mod/dna5aqi/?context=10000

I'm guessing it's Twi'lek that confused Teddy.

**Comment by FluffierThanThou** [comment]
it's actually much simpler, the request had a trailing comma in the list, so Teddy went looking for an empty string. The reason it's spread out over multiple comments is that Teddy is smart enough to split up results if he's about to hit reddits character count limits.

**Comment by FluffierThanThou** [comment]
I'll make sure Teddy doesn't go looking for empty strings

**Comment by FluffierThanThou** [comment]
fixed, thanks for reporting!
