### ISSUE TITLE
Usernames should link to RimWorld mods by that author

### ISSUE THREAD

**Issue by Mehni** [FluffierThanThou/reddit-modlinker#3]
Example, this [post](https://www.reddit.com/r/RimWorld/comments/73ai7j/please_remove_developer_console/dnoxgjv/)has a link to Krozzy's Steam profile. Instead, far more helpful would be a link to their workshop items. 

In other words, instead of linking to [this profile](https://steamcommunity.com/id/KeenKrozzy/), please link to [their collection of items](https://steamcommunity.com/id/KeenKrozzy/myworkshopfiles/?appid=294100) instead.

**Comment by FluffierThanThou** [comment]
should be easy enough, will implement
